/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f6f8fb',
        background: '#f6f8fb',
        'surface-dim': '#d7e0ea',
        'surface-bright': '#f6f8fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f5f9',
        'surface-container': '#eaf0f6',
        'surface-container-high': '#e3ebf4',
        'surface-container-highest': '#dce6f0',
        'surface-variant': '#dce6f0',
        'surface-tint': '#0b3b70',
        'on-surface': '#071a33',
        'on-surface-variant': '#52657a',
        'inverse-surface': '#001733',
        'inverse-on-surface': '#f6f8fb',
        outline: '#718399',
        'outline-variant': '#bccadb',
        primary: '#00214a',
        'on-primary': '#ffffff',
        'primary-container': '#0b3b70',
        'on-primary-container': '#d6e7f7',
        'primary-fixed': '#d3e5f6',
        'primary-fixed-dim': '#b8cbe0',
        'on-primary-fixed': '#00132b',
        'on-primary-fixed-variant': '#0b3b70',
        'inverse-primary': '#9ec0e2',
        secondary: '#365f8f',
        'on-secondary': '#ffffff',
        'secondary-container': '#dbe8f5',
        'on-secondary-container': '#183d67',
        'secondary-fixed': '#dbe8f5',
        'secondary-fixed-dim': '#bfd2e6',
        'on-secondary-fixed': '#061e38',
        'on-secondary-fixed-variant': '#274f7c',
        tertiary: '#1f9d4d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#cdf0da',
        'on-tertiary-container': '#0a4423',
        'tertiary-fixed': '#cdf0da',
        'tertiary-fixed-dim': '#8fd8ab',
        'on-tertiary-fixed': '#062a15',
        'on-tertiary-fixed-variant': '#0f5c2e',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        accent: '#1f9d4d',
        'accent-dark': '#14713a',
        'on-accent': '#ffffff',
        'party-blue': '#00214a',
        'deep-forest': '#00214a',
        'sage-growth': '#7f9dbd',
        'democrata-green': '#1f9d4d',
        'off-white': '#f6f8fb',
        'slate-gray': '#52657a',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        'container-max-width': '1280px',
        gutter: '24px',
        unit: '8px',
      },
      maxWidth: {
        'container-max-width': '1280px',
      },
      fontFamily: {
        headline: ['Montserrat', 'system-ui', 'sans-serif'],
        body: ['Libre Franklin', 'system-ui', 'sans-serif'],
        label: ['Montserrat', 'system-ui', 'sans-serif'],
        sans: ['Libre Franklin', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '1.1', fontWeight: '800' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm': ['22px', { lineHeight: '1.35', fontWeight: '700' }],
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '1.2', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
